### ISSUE TITLE
Investigate using SQLAlchemy to interface with a database

### ISSUE THREAD

**Issue by Allan-Cao** [HenrySpartGlobal/InHouseQueue#81]
Currently, all queries are hard-coded and difficult to maintain as a result. I propose we add a database ORM like SQLAlchemy implemented similarly to https://github.com/mrtolkien/inhouse_bot to manage the database and queries.

**Comment by HenrySpartGlobal** [comment]
Can I ask, are you using the public discord or are you hosting it yourself?

I understand doing database queries are useful, but could you provide me a use case that you'd need to edit the database? Are you trying to delete things? Can these things not be taken care of by more commands on the bot?
